"""song created_at

Revision ID: cbcef211eb4a
Revises: 04abd018341e
Create Date: 2022-12-31 20:41:03.480839

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'cbcef211eb4a'
down_revision = '04abd018341e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('song', 'year',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_index('ix_song_year', table_name='song')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_song_year', 'song', ['year'], unique=False)
    op.alter_column('song', 'year',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_column('song', 'created_at')
    # ### end Alembic commands ###
